server:
  port: 8082
spring:
  application:
    name: maxwell-kafka-enjoy
  profiles:
    active: dev
  kafka:
    consumer:
      enable-auto-commit: false
      session-timeout-ms: 15000
      max-poll-records: 10
      bootstrap-servers: 192.168.225.1:9092
      auto-offset-reset: earliest
    producer:
      acks: -1
      batch-size: 5
      linger-ms: 100
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://192.168.225.1:3306/maxwell?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&tinyInt1isBit=false
          username: root
          password: root
          type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 192.168.225.1
    port: 6379
    password: foobared
    timeout: 30S
    jedis:
      pool:
        max-idle: 10
        min-idle: 1
        max-active: 1000
        max-wait: 1000ms
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: elasticsearch
      cluster-nodes: 192.168.225.1:9300
mybatis-plus:
  mapper-locations: classpath:com/ssx/maxwell/kafka/enjoy/mapper/impl/*.xml
  typeAliasesPackage: com.ssx.maxwell.kafka.enjoy.common.model.entity

maxwell:
  enjoy:
    #    binlog消费队列
    kafka-binlog-topic: maxwell
    redis:
      #      对redis_mapping表的缓存
      jvmCache: true
      #      开启redis缓存binlog消费
      kafka-consumer: true
      #      默认消费组
      kafka-group: group_redis_default
      #      开启redis过期key队列消费
      expire-kafka-consumer: true
      #     过期key队列
      expire-topic: redis_expire_topic
      #     缓存重载队列
      reload-topic: redis_reload_topic
      #     过期key队列消费组
      expire-topic-kafka-group: redis_expire_topic_group
      #     缓存重载队列消费组
      reload-topic-kafka-group: redis_reload_topic_group
    elasticsearch:
      jvmCache: false
      kafka-consumer: false
      kafka-group: group_elasticsearch_default
logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    elasticsearch:
      enabled: false
